tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Kube8
  template_author: Anonymous
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.MyDeploymentPath:
    derived_from: cloudshell.nodes.CustomDeploymentOption

#    ## custom attributes example for deployment option
#    properties:
#        Image Id:
#            type: string
#            description: The id of the image to be used for deploying the app
#            default: ''

    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File