language: python
python:
    - "2.7"

install:
  - pip install -r kubernetes/test_requirements.txt
  - pip install -r kubernetes/src/requirements.txt

script:
  - nosetests kubernetes/tests --with-coverage --cover-package kubernetes/src --exclude-dir kubernetes/tests/integration