tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Kubernetes
  template_author: Alex Azarh
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
 Sample TOSCA based shell

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:
 vendor.resource.Kubernetes:
    derived_from: cloudshell.nodes.CustomCloudProvider
    capabilities:
    
      concurrent_command_capability:
        type: cloudshell.capabilities.SupportConcurrentCommands
        
      auto_discovery_capability:
        type: cloudshell.capabilities.AutoDiscovery
        properties:        
          enable_auto_discovery:
            type: boolean
            default: true
          auto_discovery_description:
            type: string
            default: Describe the auto discovery
          inventory_description:
            type: string
            default: Describe the resource shell template
          hide_address:
            type: string
            default: true

          Cluster Name:
            type: string

#          ## Attributes available from the cloud provider standard
#          Region:
#            type: string
#            default: ''
#          Networks in use:
#            type: string
#            default: ''
#          VLAN Type:
#            type: string
#            default: 'VLAN'
#          Networking type:
#            type: string
#            default: 'L2'
#
#          ## Adding custom attributes to the cloud provider discovery form
#          my_custom_attribute:
#            type: string
#            default:

#    ## Custom attributes definition
#    properties:
#      my_custom_attribute:
#        type: string
#        default:
#        description: attribute description
    properties:
      Cluster Name:
        type: string
        default:
        description: The name of the Kubernetes cluster to use.

    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File
      driver:
        file: KubernetesDriver.zip
        type: tosca.artifacts.File
      deployment:
        file: Deployments.zip
        type: tosca.artifacts.File


