tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Kubernetes
  template_author: Anonymous
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.Kubernetes Service:
    derived_from: cloudshell.nodes.CustomDeploymentOption

    properties:
      Docker Image Name:
        type: string
        description:
        tags: [user_input]
      Docker Image Tag:
        type: string
        description:
        tags: [user_input]
      Internal Ports:
        type: string
        description:
        tags: [user_input]
      External Ports:
        type: string
        description:
        tags: [user_input]
      Replicas:
        type: integer
        default: 1
        description:
        tags: [user_input]
      Start Command:
        type: string
        description:
        tags: [user_input]
      Environment Variables:
        type: string
        description: Comma separated list of 'key=value' environment variables
        tags: [user_input]
      Wait for Replicas:
        type: integer
        default: 120
        description: Wait X number of seconds during power on for all replicas to be in ready state. When the value is zero or less the shell will not wait for replicas to be ready.

      CPU Request:
        type: string
        description: The requested CPU for each container. Fractional requests are also allowed. For example '0.5'. Optional unless any resource request or limit is specified.
        tags: [user_input]
      RAM Request:
        type: string
        description: The requested RAM for each container (Optional). Memory is measured in bytes. Memory is expressed as a plain integer or as a fixed-point integer using one of these suffixes - E, P, T, G, M, K. You can also use the power-of-two equivalents - Ei, Pi, Ti, Gi, Mi, Ki. For example, '256M'.
        tags: [user_input]
      CPU Limit:
        type: string
        description: The CPU limit for each container (Optional). Fractional limits are also allowed. For example '0.5'.
        tags: [user_input]
      RAM Limit:
        type: string
        description: The RAM limit for each container (Optional). Memory is measured in bytes. Memory is expressed as a plain integer or as a fixed-point integer using one of these suffixes - E, P, T, G, M, K. You can also use the power-of-two equivalents - Ei, Pi, Ti, Gi, Mi, Ki. For example, '256M'.
        tags: [user_input]

      Wait for IP:
        type: boolean
        default: True


    #    ## custom attributes example for deployment option
#    properties:
#        Image Id:
#            type: string
#            description: The id of the image to be used for deploying the app
#            default: ''

    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File