tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Kubernetes
  template_author: Anonymous
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.Kubernetes Service:
    derived_from: cloudshell.nodes.CustomDeploymentOption

    properties:
      Docker Image Name:
        type: string
        description:
        tags: [user_input]
      Docker Image Tag:
        type: string
        description:
        tags: [user_input]
      Internal Ports:
        type: string
        description:
        tags: [user_input]
      External Ports:
        type: string
        description:
        tags: [user_input]


    #    ## custom attributes example for deployment option
#    properties:
#        Image Id:
#            type: string
#            description: The id of the image to be used for deploying the app
#            default: ''

    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File